### ISSUE TITLE
Local Setup Struggles

### ISSUE THREAD

**Issue by menhart2** [aqlaboratory/rgn2#6]
Hello,
I am trying to set up RGN2 locally to run hundreds of sequences. After setting up conda environments as illustrated in the Colab notebook, I am continually getting an error when trying to run the aminobert_predict_sequence() function. The same error occurs even when running the aminobert docker image. The error is as follows:

ERROR:tensorflow:Error recorded from prediction_loop: 2 root error(s) found.
  (0) Internal: Blas xGEMMBatched launch failed : a.shape=[12,1024,64], b.shape=[12,1024,64], m=1024, n=1024, k=64, batch_size=12
	 [[node bert/encoder/layer_0/attention/self/MatMul (defined at home/menhart/programs.installed/miniconda3/envs/rgn2/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[Sum/_1265]]
  (1) Internal: Blas xGEMMBatched launch failed : a.shape=[12,1024,64], b.shape=[12,1024,64], m=1024, n=1024, k=64, batch_size=12
	 [[node bert/encoder/layer_0/attention/self/MatMul (defined at home/menhart/programs.installed/miniconda3/envs/rgn2/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

I have seen some suggestions that it is a memory issue but after limiting the memory usage appropriately I still receive the same error. Can you point me towards what the real issue is, or perhaps suggest another approach to running many sequence predictions? 

Thank you

**Comment by christinaflo** [comment]
Hi, can you check if it works with one sequence?

To run it for multiple the sequences, you need to make a few changes:
Create a directory with your input fasta files and use the `parse_fastas` method followed by the `aminobert_predict` method in `rgn2/aminobert/prediction.py`, as opposed to `aminobert_predict_sequence` which is used in the notebook. The remainder of the workflow is the same.

**Comment by menhart2** [comment]
Hi,
Thank you for your reply. No, it does not work for a single sequence. I have been attempting to set it up locally and run it just like the test with the same string AA sequence as shown in the example, but I cannot get it to run at all. It always errors out at the aminobert_predict_sequence function with the error I reported in the github. I am beginning to suspect it is a compatibility problem with tensorflow and the RTx 3080 Ti GPU we use. I am new to working with GPUs, does this sound plausible to you? Any advice is appreciated.

Thank you,
Mary
________________________________

**Comment by christinaflo** [comment]
Yeah it is a GPU problem, it is not compatible with CUDA 10 / TF 1.15. 
I found [this](https://www.pugetsystems.com/labs/hpc/How-To-Install-TensorFlow-1-15-for-NVIDIA-RTX30-GPUs-without-docker-or-CUDA-install-2005/) source which shows you how to get TF 1.15 working with a RTx 3080 Ti GPU.
