### ISSUE TITLE
Problem with ipython during refinment

### ISSUE THREAD

**Issue by burunduk57** [aqlaboratory/rgn2#8]
I had run several predictions successfully, but last week I have a problem during refinement. I tried updating Puthon, Miniconda and ipython module, this did not change error report. Now I tried to run it on freshly installed Ubuntu system and got the same error report:

```
Traceback (most recent call last):
  File "ter2pdb/run_af2rank.py", line 14, in <module>
    from alphafold.model import model
  File "/opt/conda/envs/af2/lib/python3.7/site-packages/alphafold/model/model.py", line 64, in <module>
    class RunModel:
  File "/opt/conda/envs/af2/lib/python3.7/site-packages/alphafold/model/model.py", line 69, in RunModel
    params: Optional[Mapping[str, Mapping[str, jax.Array]]] = None):
AttributeError: module 'jax' has no attribute 'Array'

---------------------------------------------------------------------------

CalledProcessError                        Traceback (most recent call last)

[<ipython-input-6-21aed23b01ff>](https://localhost:8080/#) in <module>
     20 try:
     21   with io.capture_output() as captured:
---> 22     get_ipython().run_line_magic('shell', '{af2_env_init} && {cmd}')
     23 except subprocess.CalledProcessError:
     24   print(captured)

2 frames

[/usr/local/lib/python3.9/dist-packages/google/colab/_system_commands.py](https://localhost:8080/#) in check_returncode(self)
    135   def check_returncode(self):
    136     if self.returncode:
--> 137       raise subprocess.CalledProcessError(
    138           returncode=self.returncode, cmd=self.args, output=self.output
    139       )

CalledProcessError: Command 'source /opt/conda/etc/profile.d/conda.sh && conda init && conda activate af2 && TF_FORCE_UNIFIED_MEMORY=1 XLA_PYTHON_CLIENT_MEM_FRACTION=2.0 python ter2pdb/run_af2rank.py refine_model1 --target_list HCO_011565_ee0255 --af2_dir /content/alphafold/ --out_suffix _prediction --seq_dir aminobert_output --pdb_dir output --output_dir output --deterministic --seq_replacement - --mask_sidechains_add_cb --model_num 1 --recycles 1' returned non-zero exit status 1.
```

**Comment by sheehajh** [comment]
Yes- and I saw the same Traceback with: "AttributeError: module 'jax' has no attribute 'Array'" when running on Colab today.

Any advice appreciated!

**Comment by christinaflo** [comment]
Hey, working on this today, I will update you when it's fixed!

**Comment by christinaflo** [comment]
Okay, this is fixed now.

**Comment by yyygfgfghy** [comment]
I meet the same problem using the python 3.9.

CalledProcessError                        Traceback (most recent call last)
[<ipython-input-16-05e56bf50098>](https://localhost:8080/#) in <cell line: 20>()
     20 try:
     21   with io.capture_output() as captured:
---> 22      get_ipython().run_line_magic('shell', '{af2_env_init} && {cmd}')
     23 except subprocess.CalledProcessError:
     24   print(captured)

2 frames
[/usr/local/lib/python3.10/dist-packages/google/colab/_system_commands.py](https://localhost:8080/#) in check_returncode(self)
    135   def check_returncode(self):
    136     if self.returncode:
--> 137       raise subprocess.CalledProcessError(
    138           returncode=self.returncode, cmd=self.args, output=self.output
    139       )

CalledProcessError: Command 'source /opt/conda/etc/profile.d/conda.sh && conda init && conda activate af2 && TF_FORCE_UNIFIED_MEMORY=1 XLA_PYTHON_CLIENT_MEM_FRACTION=2.0 python ter2pdb/run_af2rank.py refine_model1 --target_list test_acaa0c --af2_dir /content/alphafold/ --out_suffix prediction --seq_dir aminobert_output --pdb_dir output --output_dir output --deterministic --seq_replacement - --mask_sidechains_add_cb --model_num 1 --recycles 1' returned non-zero exit status 1.
